apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app-flask-example
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: app
      ports:
        - name: http
          port: 8000
      publicPort: http
      monitoring: true
