apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-flask-example
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: horizontal-scaling-env
      build:
        from: horizontal-scaling
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        FLASK_APP: app.py
      environmentConfig:
        - environment: horizontal-scaling-env
          monitoring: true
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 6