apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-flask-example-job-component
spec:
  environments:
    - name: dev
      build:
        from: job-component
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        FLASK_APP: app.py
  jobs:
    - name: job1
      src: ./job
      schedulerPort: 8080