apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-flask-example
spec:
  environments:
    - name: basic-env
      build:
        from: basic
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      replicas: 3
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "200m"      
      variables:
        FLASK_APP: app.py
      environmentConfig:
        - environment: basic-env
          monitoring: true
