apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-flask-example
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: basic-env
      build:
        from: basic
    - name: multiple-replicas-env
      build:
        from: multiple-replicas
    - name: horizontal-scaling-env
      build:
        from: horizontal-scaling
    - name: monitor-resources-env
      build:
        from: monitor-resources
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        FLASK_APP: app.py
      environmentConfig:
        - environment: basic-env
          monitoring: true
        - environment: multiple-replicas-env
          monitoring: true
          replicas: 3
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
        - environment: horizontal-scaling-env
          monitoring: true
          horizontalScaling:
            minReplicas: 2
            maxReplicas: 6
        - environment: monitor-resources-env
          monitoring: true
