# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.batch_api import BatchApi  # noqa: E501


class TestBatchApi(unittest.TestCase):
    """BatchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BatchApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_batch(self) -> None:
        """Test case for create_batch

        Create batch  # noqa: E501
        """
        pass

    def test_delete_batch(self) -> None:
        """Test case for delete_batch

        Delete batch  # noqa: E501
        """
        pass

    def test_get_batch(self) -> None:
        """Test case for get_batch

        Gets batch  # noqa: E501
        """
        pass

    def test_get_batch_job(self) -> None:
        """Test case for get_batch_job

        Gets batch job  # noqa: E501
        """
        pass

    def test_get_batches(self) -> None:
        """Test case for get_batches

        Gets batches  # noqa: E501
        """
        pass

    def test_stop_batch(self) -> None:
        """Test case for stop_batch

        Stop batch  # noqa: E501
        """
        pass

    def test_stop_batch_job(self) -> None:
        """Test case for stop_batch_job

        Stop batch job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
