# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.resource_requirements import ResourceRequirements  # noqa: E501

class TestResourceRequirements(unittest.TestCase):
    """ResourceRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRequirements:
        """Test ResourceRequirements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRequirements`
        """
        model = ResourceRequirements()  # noqa: E501
        if include_optional:
            return ResourceRequirements(
                limits = {
                    'key' : ''
                    },
                requests = {
                    'key' : ''
                    }
            )
        else:
            return ResourceRequirements(
        )
        """

    def testResourceRequirements(self):
        """Test ResourceRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
