# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.job_status import JobStatus  # noqa: E501

class TestJobStatus(unittest.TestCase):
    """JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobStatus:
        """Test JobStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobStatus`
        """
        model = JobStatus()  # noqa: E501
        if include_optional:
            return JobStatus(
                batch_name = ''batch1'',
                created = '2006-01-02T15:04:05Z',
                ended = '2006-01-02T15:04:05Z',
                job_id = ''job1'',
                message = '"Error occurred"',
                name = 'calculator',
                started = '2006-01-02T15:04:05Z',
                status = 'Waiting'
            )
        else:
            return JobStatus(
                created = '2006-01-02T15:04:05Z',
                name = 'calculator',
        )
        """

    def testJobStatus(self):
        """Test JobStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
