# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.job_api import JobApi  # noqa: E501


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        Create job  # noqa: E501
        """
        pass

    def test_delete_job(self) -> None:
        """Test case for delete_job

        Delete job  # noqa: E501
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Gets job  # noqa: E501
        """
        pass

    def test_get_jobs(self) -> None:
        """Test case for get_jobs

        Gets jobs  # noqa: E501
        """
        pass

    def test_stop_job(self) -> None:
        """Test case for stop_job

        Stop job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
