# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator

class JobStatus(BaseModel):
    """
    JobStatus holds general information about job status  # noqa: E501
    """
    batch_name: Optional[StrictStr] = Field(None, alias="batchName", description="BatchName Optional Batch ID of a job")
    created: StrictStr = Field(..., description="Created timestamp")
    ended: Optional[StrictStr] = Field(None, description="Ended timestamp")
    job_id: Optional[StrictStr] = Field(None, alias="jobId", description="JobId Optional ID of a job")
    message: Optional[StrictStr] = Field(None, description="Message, if any, of the job")
    name: StrictStr = Field(..., description="Name of the job")
    started: Optional[StrictStr] = Field(None, description="Started timestamp")
    status: Optional[StrictStr] = Field(None, description="Status of the job")
    __properties = ["batchName", "created", "ended", "jobId", "message", "name", "started", "status"]

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('Waiting', 'Running', 'Succeeded', 'Stopping', 'Stopped', 'Failed', 'DeadlineExceeded'):
            raise ValueError("must be one of enum values ('Waiting', 'Running', 'Succeeded', 'Stopping', 'Stopped', 'Failed', 'DeadlineExceeded')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobStatus:
        """Create an instance of JobStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobStatus:
        """Create an instance of JobStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobStatus.parse_obj(obj)

        _obj = JobStatus.parse_obj({
            "batch_name": obj.get("batchName"),
            "created": obj.get("created"),
            "ended": obj.get("ended"),
            "job_id": obj.get("jobId"),
            "message": obj.get("message"),
            "name": obj.get("name"),
            "started": obj.get("started"),
            "status": obj.get("status")
        })
        return _obj


