# coding: utf-8

"""
    Radix job scheduler server.

    This is the API Server for the Radix job scheduler server.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, Optional
from pydantic import BaseModel, StrictStr

class ResourceRequirements(BaseModel):
    """
    More info: https://www.radix.equinor.com/references/reference-radix-config/#resources-common  # noqa: E501
    """
    limits: Optional[Dict[str, StrictStr]] = None
    requests: Optional[Dict[str, StrictStr]] = None
    __properties = ["limits", "requests"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ResourceRequirements:
        """Create an instance of ResourceRequirements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ResourceRequirements:
        """Create an instance of ResourceRequirements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ResourceRequirements.parse_obj(obj)

        _obj = ResourceRequirements.parse_obj({
            "limits": obj.get("limits"),
            "requests": obj.get("requests")
        })
        return _obj


